/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    builds: Build;
    team: Team;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    builds: BuildsSelect<false> | BuildsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every page on the site, built from sections you can add, reorder and remove. The front page is the one called Home. Your work saves automatically as a draft; nothing is public until you click Publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * What staff call it, e.g. "FAQ". Used in this list and to fill in the web address.
   */
  title: string;
  /**
   * One or two words in capitals, e.g. "Service Department".
   */
  eyebrow?: string | null;
  /**
   * The big headline at the top of the page. Say what the visitor gets, not what the page is. Leave blank when the page starts with a Hero section, which has its own.
   */
  heading?: string | null;
  /**
   * Optional. Two or three sentences under the heading. Type {builds} for the number of finished builds; it updates itself.
   */
  intro?: string | null;
  /**
   * Add sections with the button below. Drag the handle on the left of a section to move it.
   */
  sections?:
    | (
        | {
            /**
             * Optional. A heading shown above this section.
             */
            heading?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            /**
             * Optional. A heading shown above this section.
             */
            heading?: string | null;
            items?:
              | {
                  title: string;
                  text: string;
                  highlight?: {
                    to?: ('calendar' | 'sales' | 'service' | 'email' | 'map' | 'builder' | 'custom') | null;
                    /**
                     * A page on this site like /financing/, or a full address like https://...
                     */
                    url?: string | null;
                    /**
                     * Optional. Blank uses the phone number, email or a standard label.
                     */
                    text?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cards';
          }
        | {
            /**
             * Optional. A heading shown above this section.
             */
            heading?: string | null;
            items?:
              | {
                  title: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            /**
             * Optional. A heading shown above this section.
             */
            heading?: string | null;
            /**
             * Each question opens to show its answer. Google can show these in search results.
             */
            items?:
              | {
                  question: string;
                  answer: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            /**
             * Optional. A heading shown above this section.
             */
            heading?: string | null;
            items?:
              | {
                  text: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checklist';
          }
        | {
            /**
             * A shaded box. Start with a bold sentence, then explain.
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'note';
          }
        | {
            heading: string;
            /**
             * As it should read, e.g. "$200,000 - $300,000".
             */
            price: string;
            /**
             * Optional. What the price includes.
             */
            note?: string | null;
            items?:
              | {
                  title: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'priceBox';
          }
        | {
            /**
             * Optional. A heading shown above this section.
             */
            heading?: string | null;
            /**
             * Optional. Type {builds} for the number of finished builds or {team} for the number of people on the team; they update themselves.
             */
            intro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            /**
             * Optional. A heading shown above this section.
             */
            heading?: string | null;
            items?:
              | {
                  /**
                   * e.g. "March 2020" or just "2024".
                   */
                  when: string;
                  title: string;
                  text: string;
                  /**
                   * Tick until the date is confirmed. The pre-launch check lists every ticked milestone.
                   */
                  provisional?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            style?: ('box' | 'band') | null;
            eyebrow?: string | null;
            /**
             * Optional, but most calls to action read better with one.
             */
            heading?: string | null;
            /**
             * One or two short lines under the heading.
             */
            text?: string | null;
            button: {
              to: 'calendar' | 'sales' | 'service' | 'email' | 'map' | 'builder' | 'custom';
              /**
               * A page on this site like /financing/, or a full address like https://...
               */
              url?: string | null;
              /**
               * Optional. Blank uses the phone number, email or a standard label.
               */
              text?: string | null;
            };
            secondButton?: {
              to?: ('calendar' | 'sales' | 'service' | 'email' | 'map' | 'builder' | 'custom') | null;
              /**
               * A page on this site like /financing/, or a full address like https://...
               */
              url?: string | null;
              /**
               * Optional. Blank uses the phone number, email or a standard label.
               */
              text?: string | null;
            };
            /**
             * Optional. Usually a second way in, like "Or call (480) 761-7175."
             */
            smallPrint?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Optional. Up to three cut-outs with transparent backgrounds (PNG). One shows per visit, the next one each time the visitor comes back, rising out of the bottom-right corner as the box scrolls into view. The text moves to the left.
             */
            people?: (number | Media)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            /**
             * Optional. A heading shown above this section.
             */
            heading?: string | null;
            /**
             * Optional. One line above the form.
             */
            intro?: string | null;
            /**
             * Both forms are edited in HubSpot. Blank means the sales form.
             */
            preset?: ('conversion' | 'service') | null;
            /**
             * Shows this HubSpot form instead: the data-form-id from its embed code, e.g. "c2d5806e-8f73-4932-a720-f10ac6dbc66a". Set "Which form" to Service request for a service form, so its leads are reported as service.
             */
            formId?: string | null;
            /**
             * HubSpot styles each form itself. Tick this for a form with dark text; leave it for one with white text, which sits on navy.
             */
            lightCard?: boolean | null;
            /**
             * Optional. Lets a button elsewhere scroll here: "service-department" is reached with /contact-us/#service-department. Blank is #contact-form.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            /**
             * Fills the whole screen behind the words. Use a wide photo at least 1920 pixels across, with calm space where the text sits.
             */
            image: number | Media;
            /**
             * The first thing anyone reads. Press Enter to break it onto a second line.
             */
            heading: string;
            text?: string | null;
            /**
             * A YouTube link, or the address of a short .mp4 clip (desktop only, under 20 seconds and a few MB). It plays silently on a loop behind the words; the photo shows while it loads, and on phones for a clip.
             */
            video?: string | null;
            /**
             * The data-form-id from a HubSpot embed code. The form sits in a white card to the right of the heading, and the buttons are hidden. The "2026 - Which Build Fits You" quiz (d85f2b90-5a81-49c9-8972-a55b714287fe) also shows the buyer their matching build tier when they finish.
             */
            formId?: string | null;
            button?: {
              to?: ('calendar' | 'sales' | 'service' | 'email' | 'map' | 'builder' | 'custom') | null;
              /**
               * A page on this site like /financing/, or a full address like https://...
               */
              url?: string | null;
              /**
               * Optional. Blank uses the phone number, email or a standard label.
               */
              text?: string | null;
            };
            secondButton?: {
              to?: ('calendar' | 'sales' | 'service' | 'email' | 'map' | 'builder' | 'custom') | null;
              /**
               * A page on this site like /financing/, or a full address like https://...
               */
              url?: string | null;
              /**
               * Optional. Blank uses the phone number, email or a standard label.
               */
              text?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Optional, e.g. "What we do".
             */
            eyebrow?: string | null;
            /**
             * One plain sentence about what we do.
             */
            heading: string;
            /**
             * A transparent PNG exactly the size of the big photo, with the van where it sits in that photo, so the two line up. home-what-we-do-van-aligned is the current one.
             */
            revealFront?: (number | null) | Media;
            /**
             * Optional. A transparent PNG the size of the big photo holding only a strip of ground, so the tyres rest on something before the forest comes in. It shows only where the forest has not been revealed. home-what-we-do-ground is the current one.
             */
            revealGround?: (number | null) | Media;
            /**
             * Above is calmer; over works when the photo has a plain area on the left. Ignored for a cut-out, where the words always sit beside it.
             */
            headingPlacement?: ('above' | 'over') | null;
            /**
             * Optional. A few words each, e.g. "RVIA certified". Shown in one line, separated by dots.
             */
            proof?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Cut-out needs a PNG with a transparent background. Reveal needs both: the full photo as the big photo, and the cut-out below.
             */
            imageStyle?: ('photo' | 'cutout' | 'reveal') | null;
            /**
             * Full photo: a wide one, at least 1920 pixels across. Cut-out: the van alone on a transparent background. The forest photo is home-what-we-do-1 in the Media Library.
             */
            image: number | Media;
            /**
             * Up to six, shown in one row under the big photo. Drag to reorder.
             */
            photos?: (number | Media)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'photoShowcase';
          }
        | {
            heading: string;
            intro?: string | null;
            /**
             * Optional. Lets a button elsewhere scroll here: a name of "two-ways" is reached with #two-ways.
             */
            anchor?: string | null;
            items?:
              | {
                  /**
                   * Optional. Shown across the top of the card, cropped to a wide 2:1 shape.
                   */
                  image?: (number | null) | Media;
                  /**
                   * Plays silently on a loop in place of the picture, which still shows while it loads. MP4, under 1 MB.
                   */
                  video?: (number | null) | Media;
                  /**
                   * The option's name, e.g. "Tailored".
                   */
                  title: string;
                  kicker?: string | null;
                  text: string;
                  priceLabel?: string | null;
                  price: string;
                  button: {
                    to: 'calendar' | 'sales' | 'service' | 'email' | 'map' | 'builder' | 'custom';
                    /**
                     * A page on this site like /financing/, or a full address like https://...
                     */
                    url?: string | null;
                    /**
                     * Optional. Blank uses the phone number, email or a standard label.
                     */
                    text?: string | null;
                  };
                  /**
                   * Gold border and a gold button. Use on one card at most.
                   */
                  featured?: boolean | null;
                  /**
                   * e.g. "Most Popular".
                   */
                  flag?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pathCards';
          }
        | {
            heading: string;
            intro?: string | null;
            button?: {
              to?: ('calendar' | 'sales' | 'service' | 'email' | 'map' | 'builder' | 'custom') | null;
              /**
               * A page on this site like /financing/, or a full address like https://...
               */
              url?: string | null;
              /**
               * Optional. Blank uses the phone number, email or a standard label.
               */
              text?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'vanTour';
          }
        | {
            image: number | Media;
            imageSide?: ('left' | 'right') | null;
            /**
             * Optional. A short line under the photo.
             */
            caption?: string | null;
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            button?: {
              to?: ('calendar' | 'sales' | 'service' | 'email' | 'map' | 'builder' | 'custom') | null;
              /**
               * A page on this site like /financing/, or a full address like https://...
               */
              url?: string | null;
              /**
               * Optional. Blank uses the phone number, email or a standard label.
               */
              text?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            heading: string;
            /**
             * Type {builds} for the number of finished builds or {team} for the number of people on the team; they update themselves.
             */
            text?: string | null;
            button?: {
              to?: ('calendar' | 'sales' | 'service' | 'email' | 'map' | 'builder' | 'custom') | null;
              /**
               * A page on this site like /financing/, or a full address like https://...
               */
              url?: string | null;
              /**
               * Optional. Blank uses the phone number, email or a standard label.
               */
              text?: string | null;
            };
            /**
             * Up to three photos shown large. The rest of the wall fills itself from the Build Gallery.
             */
            featured?: (number | Media)[] | null;
            /**
             * Optional. Small photos placed among the build photos, near the top where they are seen. Use them to break up a run of van exteriors. They do not link anywhere.
             */
            mixIn?: (number | Media)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'photoWall';
          }
        | {
            heading: string;
            intro?: string | null;
            /**
             * Scroll slowly across the page. Use the customer's words exactly as they wrote them.
             */
            items?:
              | {
                  quote: string;
                  /**
                   * As they agreed to be named, e.g. "Debi L."
                   */
                  name: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'buildGallery';
          }
        | {
            heading: string;
            /**
             * A blank line starts a new paragraph.
             */
            intro?: string | null;
            chassisLine?: string | null;
            /**
             * Added to every tier's price, so the numbers include the van. Dollars, no commas.
             */
            vanAllowance?: number | null;
            priceNote?: string | null;
            cardsHeading?: string | null;
            /**
             * Shown cheapest first, whatever the order here.
             */
            tiers?:
              | {
                  name: string;
                  /**
                   * e.g. "The Luxury Explorer".
                   */
                  tagline?: string | null;
                  /**
                   * The conversion alone, in dollars, no commas. The van allowance is added on the page.
                   */
                  price: number;
                  /**
                   * Two sentences at most.
                   */
                  summary?: string | null;
                  specs?:
                    | {
                        /**
                         * e.g. "400Ah"
                         */
                        value: string;
                        /**
                         * e.g. "Lithium battery"
                         */
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  /**
                   * The floor plan page, e.g. /zion/. Leave empty and the button books a call instead.
                   */
                  link?: string | null;
                  photo: number | Media;
                  art: 'rainier' | 'mckinley' | 'zion' | 'olympus' | 'el-capitan';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'buildTiers';
          }
        | {
            name: string;
            /**
             * e.g. "The Weekend Warrior".
             */
            tagline?: string | null;
            /**
             * The conversion alone, dollars, no commas. Match the Build Tiers page.
             */
            price: number;
            /**
             * Added to the build price, so the number shown includes the van.
             */
            vanAllowance?: number | null;
            priceNote?: string | null;
            heroPhoto: number | Media;
            stats?:
              | {
                  /**
                   * e.g. "400Ah"
                   */
                  value: string;
                  /**
                   * e.g. "Lithium battery"
                   */
                  label: string;
                  id?: string | null;
                }[]
              | null;
            introHeading?: string | null;
            /**
             * A blank line starts a new paragraph.
             */
            intro?: string | null;
            introPhoto?: (number | null) | Media;
            /**
             * One tab each: Kitchen, Electricity, Plumbing...
             */
            features?:
              | {
                  name: string;
                  photo?: (number | null) | Media;
                  /**
                   * One item per line.
                   */
                  items?: string | null;
                  id?: string | null;
                }[]
              | null;
            interiorPhotos?: (number | Media)[] | null;
            exteriorPhotos?: (number | Media)[] | null;
            /**
             * The same on every tier page today, so change it on all five.
             */
            packages?:
              | {
                  name: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * The same on every tier page today, so change it on all five.
             */
            alaCarte?:
              | {
                  name: string;
                  /**
                   * One per line.
                   */
                  items?: string | null;
                  id?: string | null;
                }[]
              | null;
            builds?: (number | Build)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tierPage';
          }
        | {
            /**
             * Drag to reorder. A transparent PNG or WebP with the empty margin trimmed off looks best; sizes even out on their own.
             */
            logos: (number | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoStrip';
          }
      )[]
    | null;
  /**
   * The blue link in search results. Blank uses the main heading (or the page name) followed by "| Papago Vans". Keep it under 60 characters.
   */
  seoTitle?: string | null;
  /**
   * The grey text under the link. One or two sentences; Google cuts off around 155 characters.
   */
  seoDescription?: string | null;
  /**
   * papagovans.com/this-part/. Filled in from the page name when you first save; "home" is the front page. Changing it after publishing breaks links people already have.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every photo and video on the site. Upload photos straight from a phone or camera: they are resized and compressed automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the photo shows, in a sentence. Read aloud to blind visitors and used by Google. Example: "Galley with walnut countertop and induction cooktop".
   */
  alt: string;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cardAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    largeAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Finished vans. Each one gets its own page and appears in the Build Gallery and on the home page's photo wall, newest first. Your work saves automatically as a draft; nothing is public until you click Publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builds".
 */
export interface Build {
  id: number;
  /**
   * The name the owners gave it, e.g. "Sky Lounge".
   */
  title: string;
  /**
   * Drag to reorder. The first photo is the main one: it leads the page and is the picture in the gallery, so make it the whole van. A build with no photos stays out of the gallery.
   */
  photos?: (number | Media)[] | null;
  /**
   * One or two sentences: the chassis, the floor plan, what makes it this owner's van. Shown in Google results.
   */
  summary: string;
  /**
   * The full write-up: who it was built for, the systems in it, what is unusual about it.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * papagovans.com/projects/this-part/. Filled in from the build name when you first save. Changing it after publishing breaks links people already have.
   */
  slug?: string | null;
  /**
   * Builds are listed newest first.
   */
  finished: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Articles on the Guides page. Your work saves automatically as a draft; nothing is public until you click Publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * One or two sentences on what the reader will learn. Shown under the title on the Guides page and in Google results. Google cuts off around 155 characters.
   */
  summary: string;
  /**
   * Optional. The main photo for the post.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Use Heading 2 for main sections and Heading 3 inside them. Add a photo with the image button in the toolbar, or by typing /image.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * The blue link in search results. Blank uses the post title followed by "| Papago Vans". Keep it under 60 characters.
   */
  seoTitle?: string | null;
  /**
   * papagovans.com/blog/this-part/. Filled in from the title when you first save. Changing it after publishing breaks links people already have.
   */
  slug?: string | null;
  /**
   * Shown on the post. Guides are listed newest first.
   */
  publishedDate: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * The people on the About page. Drag the handle on the left of a row to change the order within a department. Removing someone takes them off the page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  _order?: string | null;
  /**
   * As it should appear, e.g. "Jerry Suhrstedt" or just "Tim".
   */
  name: string;
  /**
   * Untick when someone leaves. They come off the About page but their photo and details are kept, so ticking it again brings them back.
   */
  active?: boolean | null;
  /**
   * Optional. Leave blank if not known yet.
   */
  role?: string | null;
  /**
   * Optional. Anyone without one is shown in a Team row at the end.
   */
  department?:
    | (
        | 'Owners'
        | 'Administration'
        | 'Finance'
        | 'Sales'
        | 'Marketing'
        | 'Builders'
        | 'Service Department'
        | 'Painters'
        | 'Inventory'
        | 'CNC Specialists'
      )
    | null;
  /**
   * A head-and-shoulders photo. Any shape works: it is cropped to a circle on the page. Without one, a plain blue circle shows until a photo is added.
   */
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Who can sign in. To add someone, create them here with a starting password and send it to them; they can change it under their own account.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'builds';
        value: number | Build;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  eyebrow?: T;
  heading?: T;
  intro?: T;
  sections?:
    | T
    | {
        text?:
          | T
          | {
              heading?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        cards?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    highlight?:
                      | T
                      | {
                          to?: T;
                          url?: T;
                          text?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        checklist?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        note?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        priceBox?:
          | T
          | {
              heading?: T;
              price?: T;
              note?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              heading?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    when?: T;
                    title?: T;
                    text?: T;
                    provisional?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              style?: T;
              eyebrow?: T;
              heading?: T;
              text?: T;
              button?:
                | T
                | {
                    to?: T;
                    url?: T;
                    text?: T;
                  };
              secondButton?:
                | T
                | {
                    to?: T;
                    url?: T;
                    text?: T;
                  };
              smallPrint?: T;
              people?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              heading?: T;
              intro?: T;
              preset?: T;
              formId?: T;
              lightCard?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              image?: T;
              heading?: T;
              text?: T;
              video?: T;
              formId?: T;
              button?:
                | T
                | {
                    to?: T;
                    url?: T;
                    text?: T;
                  };
              secondButton?:
                | T
                | {
                    to?: T;
                    url?: T;
                    text?: T;
                  };
              id?: T;
              blockName?: T;
            };
        photoShowcase?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              revealFront?: T;
              revealGround?: T;
              headingPlacement?: T;
              proof?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              imageStyle?: T;
              image?: T;
              photos?: T;
              id?: T;
              blockName?: T;
            };
        pathCards?:
          | T
          | {
              heading?: T;
              intro?: T;
              anchor?: T;
              items?:
                | T
                | {
                    image?: T;
                    video?: T;
                    title?: T;
                    kicker?: T;
                    text?: T;
                    priceLabel?: T;
                    price?: T;
                    button?:
                      | T
                      | {
                          to?: T;
                          url?: T;
                          text?: T;
                        };
                    featured?: T;
                    flag?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        vanTour?:
          | T
          | {
              heading?: T;
              intro?: T;
              button?:
                | T
                | {
                    to?: T;
                    url?: T;
                    text?: T;
                  };
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              image?: T;
              imageSide?: T;
              caption?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              content?: T;
              button?:
                | T
                | {
                    to?: T;
                    url?: T;
                    text?: T;
                  };
              id?: T;
              blockName?: T;
            };
        photoWall?:
          | T
          | {
              heading?: T;
              text?: T;
              button?:
                | T
                | {
                    to?: T;
                    url?: T;
                    text?: T;
                  };
              featured?: T;
              mixIn?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        buildGallery?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        buildTiers?:
          | T
          | {
              heading?: T;
              intro?: T;
              chassisLine?: T;
              vanAllowance?: T;
              priceNote?: T;
              cardsHeading?: T;
              tiers?:
                | T
                | {
                    name?: T;
                    tagline?: T;
                    price?: T;
                    summary?: T;
                    specs?:
                      | T
                      | {
                          value?: T;
                          label?: T;
                          id?: T;
                        };
                    link?: T;
                    photo?: T;
                    art?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        tierPage?:
          | T
          | {
              name?: T;
              tagline?: T;
              price?: T;
              vanAllowance?: T;
              priceNote?: T;
              heroPhoto?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              introHeading?: T;
              intro?: T;
              introPhoto?: T;
              features?:
                | T
                | {
                    name?: T;
                    photo?: T;
                    items?: T;
                    id?: T;
                  };
              interiorPhotos?: T;
              exteriorPhotos?: T;
              packages?:
                | T
                | {
                    name?: T;
                    description?: T;
                    id?: T;
                  };
              alaCarte?:
                | T
                | {
                    name?: T;
                    items?: T;
                    id?: T;
                  };
              builds?: T;
              id?: T;
              blockName?: T;
            };
        logoStrip?:
          | T
          | {
              logos?: T;
              id?: T;
              blockName?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  featuredImage?: T;
  body?: T;
  seoTitle?: T;
  slug?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builds_select".
 */
export interface BuildsSelect<T extends boolean = true> {
  title?: T;
  photos?: T;
  summary?: T;
  description?: T;
  slug?: T;
  finished?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  active?: T;
  role?: T;
  department?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cardAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        largeAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}